const VOCABULARY_DATA = [
    { word: "Beautiful", ipa: "[ˈbjuːtɪfl]", chinese: "美麗的", sentence: "The rainbow is beautiful after the rain.", translation: "雨後的彩虹真美麗。" },
    { word: "Breakfast", ipa: "[ˈbrekfəst]", chinese: "早餐", sentence: "We usually have eggs and milk for breakfast.", translation: "我們早餐通常吃蛋和喝牛奶。" },
    { word: "Calendar", ipa: "[ˈkælɪndər]", chinese: "日曆", sentence: "Please check the date on the calendar.", translation: "請查看日曆上的日期。" },
    { word: "Century", ipa: "[ˈsentʃəri]", chinese: "世紀", sentence: "We are living in the 21st century.", translation: "我們生活在 21 世紀。" },
    { word: "Chocolate", ipa: "[ˈtʃɒklət]", chinese: "巧克力", sentence: "My sister likes to eat chocolate ice cream.", translation: "我妹妹喜歡吃巧克力冰淇淋。" },
    { word: "Delicious", ipa: "[dɪˈlɪʃəs]", chinese: "美味的", sentence: "My mother cooked a delicious dinner tonight.", translation: "我媽媽今晚煮了一頓美味的晚餐。" },
    { word: "Dictionary", ipa: "[ˈdɪkʃənəri]", chinese: "字典", sentence: "You can look up new words in the dictionary.", translation: "你可以在字典裡查生字。" },
    { word: "Elephant", ipa: "[ˈelɪfənt]", chinese: "大象", sentence: "The elephant is the largest land animal.", translation: "大象是陸地上最大的動物。" },
    { word: "Exercise", ipa: "[ˈeksəsaɪz]", chinese: "運動/練習", sentence: "It's important to exercise every day.", translation: "每天運動是很重要的。" },
    { word: "Favorite", ipa: "[ˈfeɪvərɪt]", chinese: "最喜愛的", sentence: "Blue is my favorite color.", translation: "藍色是我最喜歡的顏色。" },
    { word: "Friday", ipa: "[ˈfraɪdeɪ]", chinese: "星期五", sentence: "We always have music class on Friday.", translation: "我們星期五總是有音樂課。" },
    { word: "Healthy", ipa: "[ˈhelθi]", chinese: "健康的", sentence: "Eating fruits and vegetables keeps you healthy.", translation: "吃蔬果能讓你保持健康。" },
    { word: "History", ipa: "[ˈhɪstri]", chinese: "歷史", sentence: "I love learning about famous people in history.", translation: "我喜歡學習歷史上的名人。" },
    { word: "Holiday", ipa: "[ˈhɒlədeɪ]", chinese: "假期", sentence: "Christmas is my favorite holiday.", translation: "聖誕節是我最喜歡的假期。" },
    { word: "Hundred", ipa: "[ˈhʌndrəd]", chinese: "一百", sentence: "There are one hundred cents in a dollar.", translation: "一美元等於一百美分。" },
    { word: "Instead", ipa: "[ɪnˈsted]", chinese: "代替", sentence: "Let's go for a walk instead of watching TV.", translation: "我們去散步不要看電視了。" },
    { word: "Interesting", ipa: "[ˈɪntrəstɪŋ]", chinese: "有趣的", sentence: "This story book is very interesting.", translation: "這本故事書非常有趣。" },
    { word: "January", ipa: "[ˈdʒænjuəri]", chinese: "一月", sentence: "New Year's Day is on January 1st.", translation: "元旦是在一月一日。" },
    { word: "Kitchen", ipa: "[ˈkɪtʃɪn]", chinese: "廚房", sentence: "Dad is making soup in the kitchen.", translation: "爸爸正在廚房煮湯。" },
    { word: "Language", ipa: "[ˈlæŋɡwɪdʒ]", chinese: "語言", sentence: "English is a very useful language.", translation: "英語是一種非常有用的語言。" },
    { word: "Library", ipa: "[ˈlaɪbrəri]", chinese: "圖書館", sentence: "We can borrow many books from the library.", translation: "我們可以從圖書館借很多書。" },
    { word: "Medicine", ipa: "[ˈmedsn]", chinese: "藥", sentence: "You should take medicine when you are sick.", translation: "生病時應該要吃藥。" },
    { word: "Mountain", ipa: "[ˈmaʊntən]", chinese: "山", sentence: "We went hiking in the mountain last weekend.", translation: "我們上週末去山裡健行。" },
    { word: "Neighbor", ipa: "[ˈneɪbər]", chinese: "鄰居", sentence: "Mr. Lin is our friendly neighbor.", translation: "林先生是我們友善的鄰居。" },
    { word: "Notebook", ipa: "[ˈnəʊtbʊk]", chinese: "筆記本", sentence: "Write down the homework in your notebook.", translation: "把作業寫在你的筆記本上。" },
    { word: "October", ipa: "[ɒkˈtəʊbər]", chinese: "十月", sentence: "Double Tenth Day is in October.", translation: "雙十節是在十月。" },
    { word: "Pancake", ipa: "[ˈpænkeɪk]", chinese: "鬆餅", sentence: "I like pancakes with honey for breakfast.", translation: "我喜歡早餐吃加蜂蜜的鬆餅。" },
    { word: "Passenger", ipa: "[ˈpæsɪndʒər]", chinese: "乘客", sentence: "The bus driver waits for every passenger.", translation: "公車司機等待每一位乘客。" },
    { word: "Pencil", ipa: "[ˈpensl]", chinese: "鉛筆", sentence: "Can I borrow your pencil, please?", translation: "我可以借你的鉛筆嗎？" },
    { word: "Picture", ipa: "[ˈpɪktʃər]", chinese: "圖畫/照片", sentence: "Let's take a picture of this beautiful flower.", translation: "我們幫這朵漂亮的花拍張照吧。" },
    { word: "Practice", ipa: "[ˈpræktɪs]", chinese: "練習", sentence: "Practice makes perfect.", translation: "熟能生巧。" },
    { word: "Question", ipa: "[ˈkwestʃən]", chinese: "問題", sentence: "Please raise your hand if you have a question.", translation: "如果你有問題請舉手。" },
    { word: "Railway", ipa: "[ˈreɪlweɪ]", chinese: "鐵路", sentence: "The train runs on the long railway.", translation: "火車在長長的鐵路上行駛。" },
    { word: "Remember", ipa: "[rɪˈmembər]", chinese: "記得", sentence: "Please remember to bring your umbrella.", translation: "請記得帶你的傘。" },
    { word: "Sandwich", ipa: "[ˈsænwɪtʃ]", chinese: "三明治", sentence: "I made a ham sandwich for lunch.", translation: "我午餐做了一個火腿三明治。" },
    { word: "Saturday", ipa: "[ˈsætədeɪ]", chinese: "星期六", sentence: "I go to the park with my dog on Saturday.", translation: "我星期六帶我的狗去公園。" },
    { word: "Science", ipa: "[ˈsaɪəns]", chinese: "科學", sentence: "We did an interesting experiment in science class.", translation: "我們在科學課做了一個有趣的實驗。" },
    { word: "Seaside", ipa: "[ˈsiːsaɪd]", chinese: "海邊", sentence: "We love to play with sand at the seaside.", translation: "我們喜歡在海邊玩沙。" },
    { word: "Shoulder", ipa: "[ˈʃəʊldər]", chinese: "肩膀", sentence: "The boy sat on his father's shoulders.", translation: "小男孩坐在他爸爸的肩膀上。" },
    { word: "Station", ipa: "[ˈsteɪʃn]", chinese: "車站", sentence: "Wait for me at the train station.", translation: "在火車站等我。" },
    { word: "Student", ipa: "[ˈstjuːdnt]", chinese: "學生", sentence: "I am a student in the fifth grade.", translation: "我是五年級的學生。" },
    { word: "Subject", ipa: "[ˈsʌbdʒɪkt]", chinese: "科目", sentence: "My favorite subject is English.", translation: "我最喜歡的科目是英文。" },
    { word: "Telephone", ipa: "[ˈtelɪfəʊn]", chinese: "電話", sentence: "Can I use your telephone to call my mom?", translation: "我可以用你的電話打給我媽媽嗎？" },
    { word: "Thursday", ipa: "[ˈθɜːzdeɪ]", chinese: "星期四", sentence: "We have a swimming class on Thursday.", translation: "我們星期四有游泳課。" },
    { word: "Tomorrow", ipa: "[təˈmɒrəʊ]", chinese: "明天", sentence: "Tomorrow will be a sunny day.", translation: "明天會是一個晴天。" },
    { word: "Tuesday", ipa: "[ˈtjuːzdeɪ]", chinese: "星期二", sentence: "I have a violin lesson every Tuesday.", translation: "我每個星期二都有小提琴課。" },
    { word: "Umbrella", ipa: "[ʌmˈbrelə]", chinese: "雨傘", sentence: "Take an umbrella because it's raining.", translation: "因為下雨了，帶把傘吧。" },
    { word: "Vacation", ipa: "[veɪˈkeɪʃn]", chinese: "假期", sentence: "We are planning a trip for summer vacation.", translation: "我們正在計畫暑假的旅行。" },
    { word: "Vegetable", ipa: "[ˈvedʒtəbl]", chinese: "蔬菜", sentence: "Eating more vegetables is good for you.", translation: "多吃蔬菜對你有好處。" },
    { word: "Wednesday", ipa: "[ˈwenzdeɪ]", chinese: "星期三", sentence: "We have an art class on Wednesday.", translation: "我們星期三有美術課。" },
    { word: "Abundant", ipa: "[əˈbʌndənt]", chinese: "豐富的", sentence: "Taiwan is abundant in tropical fruits.", translation: "台灣盛產熱帶水果。" },
    { word: "Airplane", ipa: "[ˈerpleɪn]", chinese: "飛機", sentence: "I saw an airplane flying in the sky.", translation: "我看見一架飛機在天空中飛行。" },
    { word: "Alphabet", ipa: "[ˈælfəbet]", chinese: "字母系統", sentence: "There are 26 letters in the English alphabet.", translation: "英語字母表有 26 個字母。" },
    { word: "Anything", ipa: "[ˈeniθɪŋ]", chinese: "任何事物", sentence: "You can buy anything you want here.", translation: "你在這裡可以買任何你想要的東西。" },
    { word: "Aquarium", ipa: "[əˈkweriəm]", chinese: "水族館", sentence: "We saw many colorful fish at the aquarium.", translation: "我們在水族館看到了許多色彩繽紛的魚。" },
    { word: "Backpack", ipa: "[ˈbækpæk]", chinese: "後背包", sentence: "I put my books in my backpack.", translation: "我把書放在背包裡。" },
    { word: "Balloon", ipa: "[bəˈluːn]", chinese: "氣球", sentence: "The clown is making balloon animals.", translation: "小丑正在折氣球動物。" },
    { word: "Baseball", ipa: "[ˈbeɪsbɔːl]", chinese: "棒球", sentence: "Baseball is a very popular sport in Taiwan.", translation: "棒球在台灣是一項很受歡迎的運動。" },
    { word: "Birthday", ipa: "[ˈbɜːθdeɪ]", chinese: "生日", sentence: "Today is my birthday.", translation: "今天是我生日。" },
    { word: "Busy", ipa: "[ˈbɪzi]", chinese: "忙碌的", sentence: "His father is always busy on weekdays.", translation: "他爸爸在週間總是很忙。" },
    { word: "Button", ipa: "[ˈbʌtn]", chinese: "鈕扣/按鈕", sentence: "Wait! Don't push that red button.", translation: "等一下！不要按那個紅色的按鈕。" },
    { word: "Camera", ipa: "[ˈkæmərə]", chinese: "照相機", sentence: "He likes taking photos with his camera.", translation: "他喜歡用他的照相機拍照。" },
    { word: "Cancel", ipa: "[ˈkænsl]", chinese: "取消", sentence: "They had to cancel the picnic because of the rain.", translation: "因為下雨，他們不得不取消野餐。" },
    { word: "Cancer", ipa: "[ˈkænsər]", chinese: "癌症", sentence: "Eating healthy food helps prevent cancer.", translation: "吃健康的食物有助於預防癌症。" },
    { word: "Candidate", ipa: "[ˈkændɪdət]", chinese: "候選人", sentence: "Who is the best candidate for the class leader?", translation: "誰是班長最好的候選人？" },
    { word: "Capital", ipa: "[ˈkæpɪtl]", chinese: "首都/大寫", sentence: "Taipei is the capital of Taiwan.", translation: "台北是台灣的首都。" },
    { word: "Captain", ipa: "[ˈkæptɪn]", chinese: "船長/隊長", sentence: "He is the captain of our school basketball team.", translation: "他是我們學校籃球隊的隊長。" },
    { word: "Castle", ipa: "[ˈkɑːsl]", chinese: "城堡", sentence: "The princess lived in a beautiful castle.", translation: "公主住在一座美麗的城堡裡。" },
    { word: "Celebrate", ipa: "[ˈselɪbreɪt]", chinese: "慶祝", sentence: "How are you going to celebrate your birthday?", translation: "你打算如何慶祝你的生日？" },
    { word: "Central", ipa: "[ˈsentrəl]", chinese: "中央的", sentence: "That park is in the central part of the city.", translation: "那個公園位在市中心。" },
    { word: "Character", ipa: "[ˈkærəktər]", chinese: "角色/特性", sentence: "Who is your favorite character in this movie?", translation: "誰是你電影中最喜歡的角色？" },
    { word: "Check", ipa: "[tʃek]", chinese: "檢查", sentence: "Please check your answers before you hand in the test.", translation: "交卷前請檢查你的答案。" },
    { word: "Chicken", ipa: "[ˈtʃɪkɪn]", chinese: "雞肉", sentence: "We had fried chicken for dinner.", translation: "我們晚餐吃了炸雞。" },
    { word: "Choose", ipa: "[tʃuːz]", chinese: "選擇", sentence: "Which one do you want to choose?", translation: "你想選哪一個？" },
    { word: "Church", ipa: "[tʃɜːtʃ]", chinese: "教堂", sentence: "They go to church every Sunday morning.", translation: "他們每個星期天早上都去教堂。" },
    { word: "Circle", ipa: "[ˈsɜːkl]", chinese: "圓圈", sentence: "The students are sitting in a circle.", translation: "學生們正坐成一個圓圈。" },
    { word: "Clever", ipa: "[ˈklevər]", chinese: "聰明的", sentence: "The clever boy solved the problem quickly.", translation: "那個聰明的男孩很快地解決了問題。" },
    { word: "Clock", ipa: "[klɒk]", chinese: "時鐘", sentence: "Look at the clock; it's already seven o'clock.", translation: "看那個時鐘，已經七點了。" },
    { word: "Cloudy", ipa: "[ˈklaʊdi]", chinese: "多雲的", sentence: "It's a cloudy day today; it might rain.", translation: "今天多雲，可能會下雨。" },
    { word: "Collect", ipa: "[kəˈlekt]", chinese: "收集", sentence: "My hobby is to collect old stamps.", translation: "我的嗜好是收集舊郵票。" },
    { word: "College", ipa: "[ˈkɒlɪdʒ]", chinese: "學院/大學", sentence: "He wants to go to college after he finishes high school.", translation: "高中畢業後他想上大學。" },
    { word: "Comfortable", ipa: "[ˈkʌmftəbl]", chinese: "舒服的", sentence: "This sofa is very comfortable to sit on.", translation: "這張沙發坐起來非常舒服。" },
    { word: "Compare", ipa: "[kəmˈpeər]", chinese: "比較", sentence: "Compare the two books and tell me the difference.", translation: "比較這兩本書，並告訴我差異。" },
    { word: "Complain", ipa: "[kəmˈpleɪn]", chinese: "抱怨", sentence: "She always complains about the weather.", translation: "她總是抱怨天氣。" },
    { word: "Complete", ipa: "[kəmˈpliːt]", chinese: "完成/完整的", sentence: "I hope to complete my project by Friday.", translation: "我希望能在星期五前完成我的專題。" },
    { word: "Computer", ipa: "[kəmˈpjuːtər]", chinese: "電腦", sentence: "Children like playing games on the computer.", translation: "孩子們喜歡在電腦上玩遊戲。" },
    { word: "Concern", ipa: "[kənˈsɜːn]", chinese: "擔心/關心", sentence: "Health is a major concern for elderly people.", translation: "健康對老人家來說是主要關心的事。" },
    { word: "Confirm", ipa: "[kənˈfɜːm]", chinese: "確認", sentence: "Please call to confirm your appointment.", translation: "請打電話確認你的預約。" },
    { word: "Connect", ipa: "[kəˈnekt]", chinese: "連結", sentence: "You can connect to the internet in this room.", translation: "你在這間房間可以連上網路。" },
    { word: "Continue", ipa: "[kənˈtɪnjuː]", chinese: "繼續", sentence: "Please continue reading the story.", translation: "請繼續閱讀這個故事。" },
    { word: "Control", ipa: "[kənˈtrəʊl]", chinese: "控制", sentence: "He lost control of his car on the ice.", translation: "他在冰上失去了對車子的控制。" },
    { word: "Cook", ipa: "[kʊk]", chinese: "煮飯/廚師", sentence: "My father is a very good cook.", translation: "我的父親是一位很好的廚師。" },
    { word: "Cookie", ipa: "[ˈkʊki]", chinese: "餅乾", sentence: "I ate three chocolate cookies for snack.", translation: "我點心吃了三塊巧克力餅乾。" },
    { word: "Corner", ipa: "[ˈkɔːnər]", chinese: "角落", sentence: "There is a small bookstore around the corner.", translation: "在轉角處有一間小書店。" },
    { word: "Correct", ipa: "[kəˈrekt]", chinese: "正確的", sentence: "Is this the correct answer to the question?", translation: "這是這個問題的正確答案嗎？" },
    { word: "Cost", ipa: "[kɒst]", chinese: "花費", sentence: "How much does this new bicycle cost?", translation: "這台新腳踏車要花多少錢？" },
    { word: "Cotton", ipa: "[ˈkɒtn]", chinese: "棉花", sentence: "This T-shirt is made of 100% cotton.", translation: "這件 T 恤是百分之百棉做的。" },
    { word: "County", ipa: "[ˈkaʊnti]", chinese: "縣", sentence: "We live in Pingtung County.", translation: "我們住在屏東縣。" },
    { word: "Country", ipa: "[ˈkʌntri]", chinese: "國家/鄉村", sentence: "Which country would you like to visit?", translation: "你想參觀哪一個國家？" },
    { word: "Course", ipa: "[kɔːs]", chinese: "課程", sentence: "I'm taking an English course this summer.", translation: "我今年夏天在上一門英文課。" },
    { word: "Cousin", ipa: "[ˈkʌzn]", chinese: "堂表兄弟姊妹", sentence: "My cousin from America is coming to visit us.", translation: "我美國來的堂哥要來拜訪我們。" },
    { word: "Cover", ipa: "[ˈkʌvər]", chinese: "覆蓋/蓋子", sentence: "Snow covered the ground in winter.", translation: "冬天雪覆蓋了大地。" },
    { word: "Crazy", ipa: "[ˈkreɪzi]", chinese: "發瘋的/瘋狂的", sentence: "Are you crazy? It's too dangerous.", translation: "你瘋了嗎？這太危險了。" },
    { word: "Create", ipa: "[kriˈeɪt]", chinese: "創造", sentence: "Artists use their imagination to create new things.", translation: "藝術家利用想像力來創造新事物。" },
    { word: "Credit", ipa: "[ˈkredɪt]", chinese: "信用", sentence: "Can I pay with a credit card?", translation: "我可以用信用卡付帳嗎？" },
    { word: "Crime", ipa: "[kraɪm]", chinese: "犯罪", sentence: "Stealing is a crime.", translation: "偷竊是犯罪行為。" },
    { word: "Crowd", ipa: "[kraʊd]", chinese: "人群", sentence: "There was a huge crowd at the concert.", translation: "音樂會上有一大群人。" },
    { word: "Culture", ipa: "[ˈkʌltʃər]", chinese: "文化", sentence: "We should learn about different cultures.", translation: "我們應該學習不同的文化。" },
    { word: "Curtain", ipa: "[ˈkɜːtn]", chinese: "窗簾", sentence: "Please close the curtains; it's too bright.", translation: "請拉上窗簾；太亮了。" },
    { word: "Custom", ipa: "[ˈkʌstəm]", chinese: "習俗", sentence: "Giving red envelopes is a Chinese custom.", translation: "給紅包是中國的習俗。" },
    { word: "Daily", ipa: "[ˈdeɪli]", chinese: "每日的", sentence: "Exercise should be part of your daily life.", translation: "運動應該是你日常生活的一部份。" },
    { word: "Dance", ipa: "[dɑːns]", chinese: "跳舞", sentence: "Would you like to dance with me?", translation: "你想要跟我跳舞嗎？" },
    { word: "Danger", ipa: "[ˈdeɪndʒər]", chinese: "危險", sentence: "The sign says 'Danger! Keep out!'", translation: "告示牌標示著「危險！請勿進入！」" },
    { word: "Dark", ipa: "[dɑːk]", chinese: "黑暗的", sentence: "It's getting dark; let's go home.", translation: "天快黑了，我們回家吧。" },
    { word: "Date", ipa: "[deɪt]", chinese: "日期", sentence: "What is the date today?", translation: "今天是幾月幾號？" },
    { word: "Dead", ipa: "[ded]", chinese: "死的", sentence: "The poor bird was dead on the road.", translation: "那隻可憐的鳥死在路上。" },
    { word: "Deal", ipa: "[diːl]", chinese: "交易/處理", sentence: "It's a deal! I'll buy your bike.", translation: "成交！我會買下你的腳踏車。" },
    { word: "Dear", ipa: "[dɪər]", chinese: "親愛的", sentence: "Dear Grandma, thank you for the gift.", translation: "親愛的奶奶，謝謝您的禮物。" },
    { word: "Death", ipa: "[deθ]", chinese: "死亡", sentence: "The death of his dog made him very sad.", translation: "他狗狗的死讓他非常難過。" },
    { word: "Decide", ipa: "[dɪˈsaɪd]", chinese: "決定", sentence: "I haven't decided what to eat for lunch.", translation: "我還沒決定午餐要吃什麼。" },
    { word: "Decorate", ipa: "[ˈdekəreɪt]", chinese: "裝飾", sentence: "We decorated our house for Christmas.", translation: "我們為了聖誕節裝飾我們的房子。" },
    { word: "Deep", ipa: "[diːp]", chinese: "深的", sentence: "The water in this pool is very deep.", translation: "這個泳池裡的水很深。" },
    { word: "Degree", ipa: "[dɪˈɡriː]", chinese: "度數/學位", sentence: "The temperature is 30 degrees today.", translation: "今天氣溫是三十度。" },
    { word: "Deliver", ipa: "[dɪˈlɪvər]", chinese: "遞送", sentence: "The postman delivers mail every day.", translation: "郵差每天送信。" },
    { word: "Dentist", ipa: "[ˈdentɪst]", chinese: "牙醫", sentence: "I have to see the dentist because of a toothache.", translation: "因為牙痛我得去看牙醫。" },
    { word: "Department", ipa: "[dɪˈpɑːtmənt]", chinese: "部門/系", sentence: "He works in the sales department.", translation: "他在銷售部門工作。" },
    { word: "Describe", ipa: "[dɪˈskraɪb]", chinese: "描述", sentence: "Can you describe what the man looked like?", translation: "你能描述那個人長什麼樣子嗎？" },
    { word: "Desert", ipa: "[ˈdezət]", chinese: "沙漠", sentence: "Camels can live in the desert for a long time.", translation: "駱駝可以在沙漠中生活很長一段時間。" },
    { word: "Design", ipa: "[dɪˈzaɪn]", chinese: "設計", sentence: "She is a famous clothing designer.", translation: "她是一位著名的服裝設計師。" },
    { word: "Desk", ipa: "[desk]", chinese: "書桌", sentence: "Don't leave your books on the desk.", translation: "不要把書留在書桌上。" },
    { word: "Destroy", ipa: "[dɪˈstrɔɪ]", chinese: "破壞", sentence: "The earthquake destroyed many buildings.", translation: "地震破壞了許多建築物。" },
    { word: "Detail", ipa: "[ˈdiːteɪl]", chinese: "細節", sentence: "Please tell me all the details of the story.", translation: "請告訴我這個故事的所有細節。" },
    { word: "Develop", ipa: "[dɪˈveləp]", chinese: "發展", sentence: "Exercising daily helps you develop strong muscles.", translation: "每天運動有助於你發展強健的肌肉。" },
    { word: "Diamond", ipa: "[ˈdaɪəmənd]", chinese: "鑽石", sentence: "Her engagement ring has a big diamond.", translation: "她的訂婚戒指上有一顆大鑽石。" },
    { word: "Diary", ipa: "[ˈdaɪəri]", chinese: "日記", sentence: "She writes in her diary every night.", translation: "她每天晚上都在日記本裡寫字。" },
    { word: "Difference", ipa: "[ˈdɪfrəns]", chinese: "不同之處", sentence: "What is the difference between these two?", translation: "這兩者之間有什麼不同？" },
    { word: "Direct", ipa: "[dəˈrekt]", chinese: "直接的/導向", sentence: "Is there a direct bus to the airport?", translation: "有直達機場的公車嗎？" },
    { word: "Dirty", ipa: "[ˈdɜːti]", chinese: "骯髒的", sentence: "Your hands are dirty; go wash them.", translation: "你的手很髒；去洗手吧。" },
    { word: "Discover", ipa: "[dɪˈskʌvər]", chinese: "發現", sentence: "Columbus discovered America in 1492.", translation: "哥倫布在 1492 年發現了美洲。" },
    { word: "Discuss", ipa: "[dɪˈskʌs]", chinese: "討論", sentence: "Let's discuss this problem in our next meeting.", translation: "讓我們在下一次會議中討論這個問題。" },
    { word: "Dish", ipa: "[dɪʃ]", chinese: "碟子/菜餚", sentence: "My favorite Chinese dish is kung pao chicken.", translation: "我最喜歡的中國菜是宮保雞丁。" },
    { word: "Distance", ipa: "[ˈdɪstəns]", chinese: "距離", sentence: "What is the distance between Taipei and Tainan?", translation: "台北和台南之間的距離是多少？" },
    { word: "Divide", ipa: "[dɪˈvaɪd]", chinese: "劃分/除以", sentence: "The teacher divided the class into four groups.", translation: "老師把全班分成四組。" },
    { word: "Doctor", ipa: "[ˈdɒktər]", chinese: "醫生/博士", sentence: "The doctor advised me to get more rest.", translation: "醫生建議我多休息。" },
    { word: "Doll", ipa: "[dɒl]", chinese: "玩偶", sentence: "The little girl is playing with her favorite doll.", translation: "小女孩正在玩她最喜歡的玩偶。" },
    { word: "Dollar", ipa: "[ˈdɒlər]", chinese: "元", sentence: "I only have one dollar in my pocket.", translation: "我口袋裡只有一塊錢。" },
    { word: "Dolphin", ipa: "[ˈdɒlfɪn]", chinese: "海豚", sentence: "Dolphins are very intelligent animals.", translation: "海豚是非常聰明的動物。" },
    { word: "Donkey", ipa: "[ˈdɒŋki]", chinese: "驢子", sentence: "The donkey is carrying a heavy load.", translation: "驢子馱著沉重的貨物。" },
    { word: "Door", ipa: "[dɔːr]", chinese: "門", sentence: "Please close the door after you come in.", translation: "進來後請關門。" },
    { word: "Double", ipa: "[ˈdʌbl]", chinese: "雙倍的", sentence: "I would like a double cheeseburger.", translation: "我想要一個雙層起司堡。" },
    { word: "Dragon", ipa: "[ˈdræɡən]", chinese: "龍", sentence: "The dragon is a mythical creature in many stories.", translation: "在許多故事中，龍是一種神話生物。" },
    { word: "Draw", ipa: "[drɔː]", chinese: "畫圖/拉", sentence: "He likes to draw pictures of nature.", translation: "他喜歡畫大自然的圖片。" },
    { word: "Dream", ipa: "[driːm]", chinese: "夢想/做夢", sentence: "My dream is to travel around the world.", translation: "我的夢想是環遊世界。" },
    { word: "Dress", ipa: "[dres]", chinese: "洋裝/穿衣", sentence: "She is wearing a beautiful pink dress today.", translation: "她今天穿著一件精美的粉紅色洋裝。" },
    { word: "Drink", ipa: "[drɪŋk]", chinese: "飲料/喝水", sentence: "Would you like something to drink?", translation: "你想喝點什麼嗎？" },
    { word: "Drive", ipa: "[draɪv]", chinese: "開車", sentence: "My mother drives me to school every morning.", translation: "我媽媽每天早上開車送我上學。" },
    { word: "Driver", ipa: "[ˈdraɪvər]", chinese: "司機", sentence: "He is a taxi driver in Taipei.", translation: "他是台北的一名計程車司機。" },
    { word: "Drop", ipa: "[drɒp]", chinese: "掉落/滴", sentence: "Be careful not to drop the vase.", translation: "小心不要摔破花瓶。" },
    { word: "Drug", ipa: "[drʌɡ]", chinese: "藥物/毒品", sentence: "Taking illegal drugs is very dangerous.", translation: "服用非法藥物是非常危險的。" },
    { word: "Drum", ipa: "[drʌm]", chinese: "鼓", sentence: "He plays the drums in a rock band.", translation: "他在一個搖滾樂團裡打鼓。" },
    { word: "Dry", ipa: "[draɪ]", chinese: "乾燥的", sentence: "The laundry is not dry yet.", translation: "洗好的衣服還沒乾。" },
    { word: "Duck", ipa: "[dʌk]", chinese: "鴨子", sentence: "Some ducks are swimming in the pond.", translation: "幾隻鴨子正在池塘裡游泳。" },
    { word: "Duty", ipa: "[ˈdjuːti]", chinese: "責任/義務", sentence: "It is everyone's duty to protect the environment.", translation: "保護環境是每個人的責任。" },
    { word: "Earth", ipa: "[ɜːθ]", chinese: "地球", sentence: "The Earth goes around the Sun.", translation: "地球繞著太陽公轉。" },
    { word: "Earthquake", ipa: "[ˈɜːθkweɪk]", chinese: "地震", sentence: "There was a small earthquake last night.", translation: "昨晚發生了小地震。" },
    { word: "East", ipa: "[iːst]", chinese: "東方", sentence: "The sun rises in the east.", translation: "太陽在東方升起。" },
    { word: "Easy", ipa: "[ˈiːzi]", chinese: "容易的", sentence: "This English test was quite easy.", translation: "這次英文考試相當容易。" },
    { word: "Eat", ipa: "[iːt]", chinese: "吃", sentence: "Don't forget to eat your vegetables.", translation: "不要忘記吃你的蔬菜。" },
    { word: "Edge", ipa: "[edʒ]", chinese: "邊緣", sentence: "Don't stand too close to the edge of the cliff.", translation: "不要站得離懸崖邊緣太近。" },
    { word: "Education", ipa: "[ˌedʒuˈkeɪʃn]", chinese: "教育", sentence: "Education is very important for children's future.", translation: "教育對於孩子們的未來非常重要。" },
    { word: "Effort", ipa: "[ˈefət]", chinese: "努力", sentence: "He put a lot of effort into his studies.", translation: "他在學業上付出了很大的努力。" },
    { word: "Egg", ipa: "[eɡ]", chinese: "蛋", sentence: "I usually have a fried egg for breakfast.", translation: "我通常早餐吃一個荷包蛋。" },
    { word: "Eight", ipa: "[eɪt]", chinese: "八", sentence: "A spider has eight legs.", translation: "蜘蛛有八條腿。" },
    { word: "Either", ipa: "[ˈaɪðər]", chinese: "兩者之一/也(不)", sentence: "You can choose either the red one or the blue one.", translation: "你可以選擇紅色的或藍色的。" },
    { word: "Electric", ipa: "[ɪˈlektrɪk]", chinese: "電的", sentence: "My uncle bought an electric car last month.", translation: "我叔叔上個月買了一輛電動車。" },
    { word: "Elephant", ipa: "[ˈelɪfənt]", chinese: "大象", sentence: "Elephants are the largest animals on land.", translation: "大象是陸地上最大的動物。" },
    { word: "Eleven", ipa: "[ɪˈlevn]", chinese: "十一", sentence: "There are eleven players on a soccer team.", translation: "足球隊有十一名球員。" },
    { word: "Else", ipa: "[els]", chinese: "其他的", sentence: "Would you like anything else to eat?", translation: "你還想吃別的什麼嗎？" },
    { word: "Empty", ipa: "[ˈempti]", chinese: "空的", sentence: "The bottle is empty; can you buy some milk?", translation: "瓶子是空的，你能買些牛奶嗎？" },
    { word: "End", ipa: "[end]", chinese: "結束/末端", sentence: "The movie has a happy end.", translation: "這部電影有個快樂的結局。" },
    { word: "Enemy", ipa: "[ˈenəmi]", chinese: "敵人", sentence: "The two countries used to be enemies.", translation: "這兩個國家過去曾是敵人。" },
    { word: "Energy", ipa: "[ˈenədʒi]", chinese: "能量", sentence: "Children usually have a lot of energy.", translation: "孩子們通常精力充沛。" },
    { word: "Engineer", ipa: "[ˌendʒɪˈnɪər]", chinese: "工程師", sentence: "My brother wants to be an engineer.", translation: "我哥哥想當一名工程師。" },
    { word: "English", ipa: "[ˈɪŋɡlɪʃ]", chinese: "英文", sentence: "We have an English class every morning.", translation: "我們每天早上都有一堂英文課。" },
    { word: "Enjoy", ipa: "[ɪnˈdʒɔɪ]", chinese: "享受/喜愛", sentence: "I hope you enjoy your meal.", translation: "希望你享受你的這餐飯。" },
    { word: "Enough", ipa: "[ɪˈnʌf]", chinese: "足夠的", sentence: "Do we have enough bread for breakfast?", translation: "我們的早餐有足夠的麵包嗎？" },
    { word: "Enter", ipa: "[ˈentər]", chinese: "進入", sentence: "Please knock before you enter the room.", translation: "進房間前請先敲門。" },
    { word: "Entrance", ipa: "[ˈentrəns]", chinese: "入口", sentence: "The main entrance to the building is on this side.", translation: "這棟建築的主入口在這一邊。" },
    { word: "Envelope", ipa: "[ˈenvələʊp]", chinese: "信封", sentence: "Put the letter in the envelope and mail it.", translation: "把信裝入信封裡然後寄出去。" },
    { word: "Equal", ipa: "[ˈiːkwəl]", chinese: "平等的", sentence: "Everyone should have equal rights.", translation: "每個人都應享有平等的權利。" },
    { word: "Eraser", ipa: "[ɪˈreɪsər]", chinese: "橡皮擦", sentence: "May I borrow your eraser for a second?", translation: "可以借我用一下你的橡皮擦嗎？" },
    { word: "Error", ipa: "[ˈerər]", chinese: "錯誤", sentence: "There is an error in your spelling.", translation: "你的拼字中有一個錯誤。" },
    { word: "Escape", ipa: "[ɪˈskeɪp]", chinese: "逃脫", sentence: "The bird escaped from its cage.", translation: "鳥兒從籠子裡逃走了。" },
    { word: "Even", ipa: "[ˈiːvn]", chinese: "甚至/偶數的", sentence: "He worked hard even on holidays.", translation: "即使在假日他也努力工作。" },
    { word: "Evening", ipa: "[ˈiːvnɪŋ]", chinese: "傍晚/晚上", sentence: "What are you going to do this evening?", translation: "你今晚打算做什麼？" },
    { word: "Event", ipa: "[ɪˈvent]", chinese: "事件/活動", sentence: "The school sports day is a big event.", translation: "學校的運動會是一項重大活動。" },
    { word: "Ever", ipa: "[ˈevər]", chinese: "曾經", sentence: "Have you ever been to America?", translation: "你曾經去過美國嗎？" },
    { word: "Every", ipa: "[ˈevri]", chinese: "每個", sentence: "She goes to the park every morning.", translation: "她每天早上都去公園。" },
    { word: "Evil", ipa: "[ˈiːvl]", chinese: "邪惡的", sentence: "In the story, the witch was very evil.", translation: "故事中，那個巫婆非常邪惡。" },
    { word: "Exact", ipa: "[ɪɡˈzækt]", chinese: "確切的", sentence: "Tell me the exact time he arrived.", translation: "告訴我他到達的確切時間。" },
    { word: "Exam", ipa: "[ɪɡˈzæm]", chinese: "考試", sentence: "We are preparing for the final exam.", translation: "我們正在準備期末考。" },
    { word: "Example", ipa: "[ɪɡˈzɑːmpl]", chinese: "例子/榜樣", sentence: "Can you give me an example of this rule?", translation: "你能給我這個規則的一個例子嗎？" },
    { word: "Excellent", ipa: "[ˈeksələnt]", chinese: "優異的", sentence: "You did an excellent job on your presentation.", translation: "你在簡報方面做得很優異。" },
    { word: "Except", ipa: "[ɪkˈsept]", chinese: "除了...之外", sentence: "Everyone was there except Tom.", translation: "除了湯姆之外，每個人都在場。" },
    { word: "Excite", ipa: "[ɪkˈsaɪt]", chinese: "使興奮", sentence: "The news excited all the fans.", translation: "這消息讓所有粉絲都很興奮。" },
    { word: "Excuse", ipa: "[ɪkˈskjuːs]", chinese: "藉口/原諒", sentence: "Excuse me, can you tell me the way to the station?", translation: "不好意思，你能告訴我怎麼去車站嗎？" },
    { word: "Exercise", ipa: "[ˈeksəsaɪz]", chinese: "運動/練習", sentence: "Regular exercise is good for your health.", translation: "定期運動對你的健康有益。" },
    { word: "Exhibit", ipa: "[ɪɡˈzɪbɪt]", chinese: "展覽/展示", sentence: "The museum exhibits many ancient artifacts.", translation: "這間博物館展覽了許多古文物。" },
    { word: "Exit", ipa: "[ˈeksɪt]", chinese: "出口", sentence: "Look for the emergency exit in case of fire.", translation: "火災時請找尋緊急出口。" },
    { word: "Expect", ipa: "[ɪkˈspekt]", chinese: "期待/預期", sentence: "I expect to hear from you soon.", translation: "我期待很快收到你的回音。" },
    { word: "Expensive", ipa: "[ɪkˈspensɪv]", chinese: "昂貴的", sentence: "This computer is too expensive for me to buy.", translation: "這台電腦對我來說太貴，買不起。" },
    { word: "Experience", ipa: "[ɪkˈspɪəriəns]", chinese: "經驗", sentence: "Traveling gives you a lot of experience.", translation: "旅行帶給你很多經驗。" },
    { word: "Explain", ipa: "[ɪkˈspleɪn]", chinese: "解釋", sentence: "Can you explain this math problem again?", translation: "你能再解釋一次這道數學題嗎？" },
    { word: "Express", ipa: "[ɪkˈspres]", chinese: "表達/快速的", sentence: "He uses art to express his feelings.", translation: "他用藝術來表達他的情感。" },
    { word: "Extra", ipa: "[ˈekstrə]", chinese: "額外的", sentence: "I need an extra blanket tonight.", translation: "我今晚需要一條額外的毯子。" },
    { word: "Eye", ipa: "[aɪ]", chinese: "眼睛", sentence: "Close your eyes and make a wish.", translation: "閉上你的眼睛，然後許一個願。" },
    { word: "Face", ipa: "[feɪs]", chinese: "臉/面對", sentence: "Wash your face before you go to bed.", translation: "睡覺前洗把臉吧。" },
    { word: "Fact", ipa: "[fækt]", chinese: "事實", sentence: "It's a fact that the Earth is round.", translation: "地球是圓的，這是一個事實。" },
    { word: "Factory", ipa: "[ˈfæktri]", chinese: "工廠", sentence: "They work in a toy factory.", translation: "他們在一家玩具工廠工作。" },
    { word: "Fail", ipa: "[feɪl]", chinese: "失敗/不及格", sentence: "Don't be afraid to fail; just try your best.", translation: "不要害怕失敗；盡力而為就好了。" },
    { word: "Fair", ipa: "[feər]", chinese: "公平的/市集", sentence: "That's not fair! You took two turns.", translation: "那不公平！你玩了兩次。" },
    { word: "False", ipa: "[fɔːls]", chinese: "錯誤的/假的", sentence: "Is the statement true or false?", translation: "這項陳述是正確還是錯誤的？" },
    { word: "Family", ipa: "[ˈfæməli]", chinese: "家庭", sentence: "My family always has dinner together.", translation: "我全家人總是一起吃晚餐。" },
    { word: "Famous", ipa: "[ˈfeɪməs]", chinese: "著名的", sentence: "J.K. Rowling is a famous writer.", translation: "J.K. 羅琳是一位著名的作家。" },
    { word: "Fan", ipa: "[fæn]", chinese: "電風扇/粉絲", sentence: "Turn on the fan; it's very hot.", translation: "開啟電風扇；天氣好熱。" },
    { word: "Far", ipa: "[fɑːr]", chinese: "遙遠的", sentence: "The library is not far from our school.", translation: "圖書館離我們學校不遠。" },
    { word: "Farm", ipa: "[fɑːm]", chinese: "農場", sentence: "My grandfather has a large fruit farm.", translation: "我祖父有一個大型水果農場。" },
    { word: "Farmer", ipa: "[ˈfɑːmər]", chinese: "農夫", sentence: "Farmers work very hard in the fields.", translation: "農夫在田野裡非常努力工作。" },
    { word: "Fast", ipa: "[fɑːst]", chinese: "快速的", sentence: "He can run very fast.", translation: "他能跑得很快。" },
    { word: "Fat", ipa: "[fæt]", chinese: "胖的/脂肪", sentence: "If you eat too much candy, you will get fat.", translation: "如果你吃太多糖果，你會發胖。" },
    { word: "Father", ipa: "[ˈfɑːðər]", chinese: "父親", sentence: "My father is a teacher.", translation: "我的父親是一位老師。" },
    { word: "Favor", ipa: "[ˈfeɪvər]", chinese: "恩惠/幫助", sentence: "Can you do me a favor, please?", translation: "你能幫我一個忙嗎？" },
    { word: "Favorite", ipa: "[ˈfeɪvərɪt]", chinese: "最喜愛的", sentence: "What's your favorite subject?", translation: "你最喜歡的科目是什麼？" },
    { word: "Fear", ipa: "[fɪər]", chinese: "恐懼", sentence: "She has a fear of high places.", translation: "她有懼高症。" },
    { word: "February", ipa: "[ˈfebruəri]", chinese: "二月", sentence: "Valentine's Day is in February.", translation: "情人節是在二月。" },
    { word: "Fee", ipa: "[fiː]", chinese: "費用", sentence: "How much is the entrance fee?", translation: "入場費是多少錢？" },
];

const DIALOGUE_DATA = [
    {
        title: "在餐廳點餐 (At the Restaurant)",
        dialogue: [
            { speaker: "Waiter", text: "Welcome! Are you ready to [blank]?" },
            { speaker: "Customer", text: "Yes, I would like to [blank] the chicken sandwich." },
            { speaker: "Waiter", text: "Anything [blank] to drink?" },
            { speaker: "Customer", text: "Just some [blank] water, please." }
        ],
        blanks: ["order", "have", "else", "cold"],
        options: ["order", "have", "else", "cold", "eat", "drink", "more", "hot"]
    },
    {
        title: "在圖書館 (At the Library)",
        dialogue: [
            { speaker: "Librarian", text: "Can I [blank] you?" },
            { speaker: "Student", text: "I'm looking for a book [blank] history." },
            { speaker: "Librarian", text: "We have many books on that [blank] in the back." },
            { speaker: "Student", text: "Thank you very [blank]!" }
        ],
        blanks: ["help", "about", "subject", "much"],
        options: ["help", "about", "subject", "much", "find", "for", "topic", "well"]
    },
    {
        title: "遇見朋友 (Meeting a Friend)",
        dialogue: [
            { speaker: "Alice", text: "Hi! How are you [blank]?" },
            { speaker: "Bob", text: "I'm doing [blank]. How about you?" },
            { speaker: "Alice", text: "I'm a bit [blank], actually." },
            { speaker: "Bob", text: "Oh, why? What [blank]?" }
        ],
        blanks: ["today", "well", "tired", "happened"],
        options: ["today", "well", "tired", "happened", "now", "good", "busy", "wrong"]
    },
    {
        title: "詢問路向 (Asking for Directions)",
        dialogue: [
            { speaker: "Stranger", text: "Excuse me, how do I [blank] to the train station?" },
            { speaker: "Passerby", text: "Go straight for two [blank] and turn left." },
            { speaker: "Stranger", text: "Is it [blank] from here?" },
            { speaker: "Passerby", text: "No, it's just a five-minute [blank]." }
        ],
        blanks: ["get", "blocks", "far", "walk"],
        options: ["get", "blocks", "far", "walk", "go", "streets", "near", "run"]
    }
];

// 此處略過中間生成的單字，實際應用時應包含完整的 1200 字庫。
